# Generated by Django 4.1.1 on 2023-01-06 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='レーティング')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('request_cont', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('startline', models.DateTimeField(auto_now_add=True, verbose_name='投稿時刻')),
                ('txid_request', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.DateTimeField(auto_now_add=True, verbose_name='投稿期日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fc_request.category', verbose_name='カテゴリー')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-startline'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(default='', max_length=50, verbose_name='ウォレットアドレス')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_cont', models.TextField(verbose_name='レスポンス内容')),
                ('startline', models.DateTimeField(auto_now_add=True, verbose_name='投稿時刻')),
                ('txid_response', models.CharField(blank=True, max_length=100, null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fc_request.rating', verbose_name='レーティング')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fc_request.request', verbose_name='依頼対象')),
            ],
        ),
    ]
