# Generated by Django 4.1.1 on 2023-01-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='投稿期日'),
        ),
    ]
